### ISSUE TITLE
CAT Bug in Samsara

### ISSUE THREAD

**Issue by donenrique24** [CWFC-CCFB/CAPSISMonitoring#7]
Benoit Courbaud reported the following bug:

Bonjour Mathieu,

J'ai depuis quelques temps un bug lorsque je fais tourner CAT en sortie de
Samsara2 avec mon script ScriptFlexibleSimuFormat2.java Aurais tu changé dans CAT des éléments dans l'export ou dans les espèces de référence qui pourraient expliquer ce problème ?
(J'ai fait un update et une compilation pour être sûr d'être bien à jour).

Voici le message d'erreur que je reçois :

currentDate: 2065 / runEvent: true
List of events of interest: []
ScriptFlexibleSimuFormat2, biomassParameterFilename:
lerfob/carbonbalancetool/biomassparameters/library/ipcc_2003_oakbeechsprucefir.bpf
ScriptFlexibleSimuFormat2, configurationFilename:
lerfob/carbonbalancetool/productionlines/library/ipcc2014_fr.prl
java.lang.IllegalArgumentException: No enum constant repicea.simulation.covariateproviders.treelevel.TreeStatusProvider.StatusClass.deadCut
        at java.lang.Enum.valueOf(Enum.java:238)
        at
repicea.simulation.covariateproviders.treelevel.TreeStatusProvider$StatusClass.valueOf(TreeStatusProvider.java:32)
        at
capsis.extension.modeltool.carbonstorageinra.CATTreeConnector.getStatusClass(CATTreeConnector.java:38)
        at
lerfob.carbonbalancetool.productionlines.ProductionProcessorManager.processWoodPiece(ProductionProcessorManager.java:630)
        at
lerfob.carbonbalancetool.CATTask.createEndUseWoodProductsFromWoodPieces(CATTask.java:339)
        at lerfob.carbonbalancetool.CATTask.doThisJob(CATTask.java:148)
        at
repicea.app.AbstractGenericTask.doInBackground(AbstractGenericTask.java:112)
        at
repicea.app.AbstractGenericTask.doInBackground(AbstractGenericTask.java:32)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at
repicea.app.AbstractGenericEngine$InternalWorker.run(AbstractGenericEngine.java:122)
Une erreur de ce type est survenu pendant l'ex cution de la t che GENERATE_WOODPRODUCTS : IllegalArgumentException Trouble while executing the script. Exception:
java.lang.NullPointerException
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at capsis.script.Pilot.runC4Script(Pilot.java:122)
        at capsis.script.Pilot.start(Pilot.java:111)
        at capsis.app.Starter.start(Starter.java:173)
        at capsis.app.Starter.main(Starter.java:201)
Caused by: java.lang.NullPointerException
        at
lerfob.carbonbalancetool.io.CATExportTool$InternalSwingWorker.createCarbonStockAndFluxEvolutionRecordSet(CATExportTool.java:221)
        at
lerfob.carbonbalancetool.io.CATExportTool$InternalSwingWorker.doThisJob(CATExportTool.java:96)
        at
repicea.app.AbstractGenericTask.doInBackground(AbstractGenericTask.java:112)
        at
repicea.app.AbstractGenericTask.doInBackground(AbstractGenericTask.java:32)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at
repicea.io.tools.REpiceaExportTool.createRecordSets(REpiceaExportTool.java:366)
        at
repicea.io.tools.REpiceaExportTool.exportRecordSets(REpiceaExportTool.java:553)
        at
lerfob.carbonbalancetool.io.CATExportTool.exportRecordSets(CATExportTool.java:537)
        at
samsara2.pgms.flexiblescript.ScriptFlexibleSimuFormat2.runOneSimulation(ScriptFlexibleSimuFormat2.java:851)
        at
samsara2.pgms.flexiblescript.ScriptFlexibleSimuFormat2.<init>(ScriptFlexibleSimuFormat2.java:231)
        at
samsara2.pgms.flexiblescript.ScriptFlexibleSimuFormat2.main(ScriptFlexibleSimuFormat2.java:114)
        ... 8 more

Dans mon script,  CAT est appelé par le code suivant:

// fc+bc-14.3.2023 CAT connection ---------------------------------------

                CarbonAccountingToolWrapper catWrapper = new CarbonAccountingToolWrapper(model, step);
                CAT cat = catWrapper.getCAT(); //

                // NOTE: BiomassParameters.class.getResource("") returns
                //
jar:file:/home/coligny/workspace/capsis4/ext/cat-1.2.5.jar!/lerfob/carbonbalancetool/biomassparameters/
                String biomassParameterFilename =
ObjectUtility.getRelativePackagePath(BiomassParameters.class) + "library"
                                + ObjectUtility.PathSeparator + "ipcc_2003_oakbeechsprucefir.bpf";
                cat.setBiomassParameters(biomassParameterFilename); //
                System.out.println("ScriptFlexibleSimuFormat2, biomassParameterFilename: "
+ biomassParameterFilename);

                String configurationFilename =
ObjectUtility.getRelativePackagePath(ProductionLine.class) + "library"
                                + ObjectUtility.PathSeparator + "ipcc2014_fr.prl";
                cat.setProductionManager(configurationFilename); //
                System.out.println("ScriptFlexibleSimuFormat2, configurationFilename: " + configurationFilename);

                // Unused at present time
//              setSensitivityAnalysisParameters(cat, mode);
                cat.calculateCarbon();

                CATExportTool exportTool = cat.createExportTool();
                List<Enum> exportOptions = new ArrayList<Enum>();
                exportOptions.add(CATExportTool.ExportOption.CarbonStockAndFluxEvolution);
                exportOptions.add(CATExportTool.ExportOption.TotalHWPbyCategories);
                exportOptions.add(CATExportTool.ExportOption.TotalLogVolumeByCategories);
                // BC 2023.04.27
                exportOptions.add(CATExportTool.ExportOption.HWPEvolution);
                exportTool.setSelectedOptions(exportOptions);
                // BC 2023.04.07
                // String outputFilename = outputDir + "/CAT_export.csv";
                String outputFilename = outputDir + "/Simu" + simulationId + "_CAT_.csv";
                exportTool.setFilename(outputFilename);
                exportTool.exportRecordSets();
                cat.requestShutdown();

**Comment by donenrique24** [comment]
Fixed and committed on April 26th
